export const SERVICE_OPTIONS = [
  'Payment-Gateway',
  'Auth-Service',
  'User-API',
  'Order-Service',
  'Inventory-Service',
  'Notification-Service',
  'Search-Index',
  'CDN-Edge',
  'Database-Primary',
  'Cache-Cluster',
  'Analytics-Pipeline',
  'Email-Service',
  'SMS-Gateway',
  'File-Storage',
  'API-Gateway',
]
